server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
      - id: all_route
        uri: http://localhost:8000
        predicates:
        - Path=/**

#logging:
#  level:
#    org.springframework.cloud.gateway: TRACE
#    org.springframework.http.server.reactive: DEBUG
#    org.springframework.web.reactive: DEBUG
#    reactor.ipc.netty: DEBUG
